### ISSUE TITLE
Not possible to create a classifier rule on the symmetric chain

### ISSUE THREAD

**Issue by manuelbuil** [trozet/tacker#17]
When a symmetric chain is created through tacker, ODL creates two RSPs. Howeer, from tacker only one can be seen and therefore it is not possible to create a classification rule on the traffic that comes back

**Comment by trozet** [comment]
I think what we want here is when symmetrical is defined, we get back 2 ODL chain instance ids (one for first chain, and one for reverse).  Right now we ignore the 2nd instance, but we probably want to create another chain entry in the database.  This get's a little tricky because now a user has essentially created 2 chains from one command, and would have to remember to clean up both with a delete ( or we do it for them).  This would then allow a user to create a classifier on the reverse path.
